/*
* Sketch generated by duck2spark from Marcus Mengs aka MaMe82
*
*/
#include "DigiKeyboard.h"

#define DUCK_LEN 288
const PROGMEM uint8_t duckraw [DUCK_LEN] = {
	82, 69, 77, 32, 68, 114, 111, 112, 32, 97, 32, 99, 97, 108, 108, 105, 110, 103, 32, 99, 97, 114, 100, 32, 111, 110, 32, 116, 104, 101, 32, 100, 101, 115, 107, 116, 111, 112, 32, 111, 102, 32, 97, 32, 118, 105, 99, 116, 105, 109, 13, 10, 82, 69, 77, 32, 87, 101, 32, 97, 114, 101, 32, 116, 97, 114, 103, 101, 116, 116, 105, 110, 103, 32, 119, 105, 110, 100, 111, 119, 115, 32, 49, 48, 32, 97, 110, 100, 32, 117, 112, 32, 119, 105, 116, 104, 32, 116, 104, 105, 115, 32, 115, 99, 114, 105, 112, 116, 13, 10, 82, 69, 77, 32, 65, 117, 116, 104, 111, 114, 58, 32, 90, 97, 99, 104, 32, 82, 105, 98, 97, 99, 107, 13, 10, 68, 69, 76, 65, 89, 32, 49, 48, 48, 48, 13, 10, 71, 85, 73, 32, 114, 13, 10, 68, 69, 76, 65, 89, 32, 49, 48, 48, 48, 13, 10, 83, 84, 82, 73, 78, 71, 32, 110, 111, 116, 101, 112, 97, 100, 13, 10, 69, 78, 84, 69, 82, 13, 10, 68, 69, 76, 65, 89, 32, 53, 48, 48, 48, 13, 10, 83, 84, 82, 73, 78, 71, 32, 89, 111, 117, 32, 104, 97, 118, 101, 32, 98, 101, 101, 110, 32, 104, 97, 99, 107, 101, 100, 33, 13, 10, 67, 84, 82, 76, 32, 115, 13, 10, 68, 69, 76, 65, 89, 32, 49, 48, 48, 48, 13, 10, 83, 84, 82, 73, 78, 71, 32, 100, 117, 99, 107, 121, 102, 105, 108, 101, 46, 116, 120, 116, 13, 10, 69, 78, 84, 69, 82, 13, 10, 13, 10, 13, 10, 13, 10, 13, 10
};
int i = 1; //how many times the payload should run (-1 for endless loop)
bool blink=true;

void setup()
{
	// initialize the digital pin as an output.
	pinMode(0, OUTPUT); //LED on Model B
	pinMode(1, OUTPUT); //LED on Model A
	DigiKeyboard.delay(1000); //wait 1000 milliseconds before first run, to give target time to initialize
}

void loop()
{

	//should code be runned in this loop?
	if (i != 0) {
		DigiKeyboard.sendKeyStroke(0);

		//parse raw duckencoder script
		for (int i=0; i<DUCK_LEN; i+=2)
		{
			uint8_t key = pgm_read_word_near(duckraw + i);
			uint8_t mod = pgm_read_word_near(duckraw + i+1);
			if (key == 0) //delay (a delay>255 is split into a sequence of delays)
			{
				DigiKeyboard.delay(mod);
			}
			else DigiKeyboard.sendKeyStroke(key,mod);
		}
		i--;
		DigiKeyboard.delay(5000); //wait 5000 milliseconds before next loop iteration

	}
	else if (blink)
	{
		digitalWrite(0, HIGH);   // turn the LED on (HIGH is the voltage level)
		digitalWrite(1, HIGH);
		delay(100);               // wait for a second
		digitalWrite(0, LOW);    // turn the LED off by making the voltage LOW
		digitalWrite(1, LOW);
		delay(100);               // wait for a second
	}
}
